// ------------------------------------------------------------------------
// This file is generated by ts-json-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-json-loader
// ------------------------------------------------------------------------

declare const __jsonRoot: string;
export = __jsonRoot;
