// ------------------------------------------------------------------------
// This file is generated by ts-json-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-json-loader
// ------------------------------------------------------------------------

declare const __jsonRoot: [
    {
        readonly 'null': null;
        readonly 'true': boolean;
        readonly 'false': boolean;
        readonly 'number': number;
        readonly 'string': string;
        readonly emptyArray: void[];
        readonly array: [
            number,
            number,
            number,
            number,
            number
        ];
        readonly mixedArray: [
            number,
            string,
            boolean,
            boolean,
            null,
            {
                readonly 'false': boolean;
                readonly 'number': number;
                readonly 'string': string;
            }
        ];
        readonly child1: {
            readonly 'null': null;
            readonly 'true': boolean;
            readonly 'false': boolean;
        };
        readonly child2: {
            readonly 'number': number;
            readonly 'string': string;
            readonly array: [
                number,
                number,
                number,
                number,
                number
            ];
        };
    },
    {
        readonly 'null': null;
        readonly 'true': boolean;
        readonly 'false': boolean;
        readonly 'number': number;
        readonly 'string': string;
        readonly emptyArray: void[];
        readonly array: [
            number,
            number,
            number,
            number,
            number
        ];
        readonly mixedArray: [
            number,
            string,
            boolean,
            boolean,
            null,
            {
                readonly 'false': boolean;
                readonly 'number': number;
                readonly 'string': string;
            }
        ];
        readonly child1: {
            readonly 'null': null;
            readonly 'true': boolean;
            readonly 'false': boolean;
        };
        readonly child2: {
            readonly 'number': number;
            readonly 'string': string;
            readonly array: [
                number,
                number,
                number,
                number,
                number
            ];
        };
    },
    {
        readonly 'null': null;
        readonly 'true': boolean;
        readonly 'false': boolean;
        readonly 'number': number;
        readonly 'string': string;
        readonly emptyArray: void[];
        readonly array: [
            number,
            number,
            number,
            number,
            number
        ];
        readonly mixedArray: [
            number,
            string,
            boolean,
            boolean,
            null,
            {
                readonly 'false': boolean;
                readonly 'number': number;
                readonly 'string': string;
            }
        ];
        readonly child1: {
            readonly 'null': null;
            readonly 'true': boolean;
            readonly 'false': boolean;
        };
        readonly child2: {
            readonly 'number': number;
            readonly 'string': string;
            readonly array: [
                number,
                number,
                number,
                number,
                number
            ];
        };
    }
];
export default __jsonRoot;
