// ------------------------------------------------------------------------
// This file is generated by ts-json-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-json-loader
// ------------------------------------------------------------------------

declare const __jsonRoot: {
    readonly 'null': null;
    readonly 'true': boolean;
    readonly 'false': boolean;
    readonly 'number': number;
    readonly 'string': string;
    readonly emptyArray: void[];
    readonly array: [
        number,
        number,
        number,
        number,
        number
    ];
    readonly mixedArray: [
        number,
        string,
        boolean,
        boolean,
        null,
        {
            readonly 'false': boolean;
            readonly 'number': number;
            readonly 'string': string;
        }
    ];
    readonly child1: {
        readonly 'null': null;
        readonly 'true': boolean;
        readonly 'false': boolean;
    };
    readonly child2: {
        readonly 'number': number;
        readonly 'string': string;
        readonly array: [
            number,
            number,
            number,
            number,
            number
        ];
    };
}
export default __jsonRoot;

// Named exports with top level propeties whose names are valid identifiers
export const emptyArray: void[];
export const array: [
    number,
    number,
    number,
    number,
    number
];
export const mixedArray: [
    number,
    string,
    boolean,
    boolean,
    null,
    {
        readonly 'false': boolean;
        readonly 'number': number;
        readonly 'string': string;
    }
];
export const child1: {
    readonly 'null': null;
    readonly 'true': boolean;
    readonly 'false': boolean;
};
export const child2: {
    readonly 'number': number;
    readonly 'string': string;
    readonly array: [
        number,
        number,
        number,
        number,
        number
    ];
};
