// ------------------------------------------------------------------------
// This file is generated by ts-json-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-json-loader
// ------------------------------------------------------------------------

declare const __jsonRoot: {
    readonly empty: null;
    readonly valid: boolean;
    readonly 'not-valid': boolean;
    readonly count: number;
    readonly name: string;
    readonly array: [
        null,
        boolean,
        boolean,
        number,
        string
    ];
}
export = __jsonRoot;
