// ------------------------------------------------------------------------
// This file is generated by ts-json-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-json-loader
// ------------------------------------------------------------------------

declare const __jsonRoot: {
    readonly empty: null;
    readonly valid: boolean;
    readonly 'not-valid': boolean;
    readonly count: number;
    readonly name: string;
    readonly array: [
        null,
        boolean,
        boolean,
        number,
        string
    ];
}
export default __jsonRoot;

// Named exports with top level propeties whose names are valid identifiers
export const empty: null;
export const valid: boolean;
export const count: number;
export const name: string;
export const array: [
    null,
    boolean,
    boolean,
    number,
    string
];
