// ------------------------------------------------------------------------
// This file is generated by ts-json-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-json-loader
// ------------------------------------------------------------------------

declare const __jsonRoot: {
    readonly name: string;
    readonly version: string;
    readonly description: string;
    readonly main: string;
    readonly scripts: {
        readonly 'clean:lib': string;
        readonly 'prebuild:lib': string;
        readonly 'build:lib': string;
        readonly 'clean:test': string;
        readonly 'prebuild:test': string;
        readonly 'build:test': string;
        readonly build: string;
        readonly prewatch: string;
        readonly watch: string;
        readonly pretest: string;
        readonly test: string;
        readonly prepublishOnly: string;
    };
    readonly repository: {
        readonly 'type': string;
        readonly url: string;
    };
    readonly keywords: [
        string,
        string,
        string,
        string,
        string,
        string,
        string
    ];
    readonly author: string;
    readonly license: string;
    readonly bugs: {
        readonly url: string;
    };
    readonly homepage: string;
    readonly devDependencies: {
        readonly '@types/escape-string-regexp': string;
        readonly '@types/fs-extra': string;
        readonly '@types/glob': string;
        readonly '@types/minimist': string;
        readonly '@types/mocha': string;
        readonly '@types/rimraf': string;
        readonly '@types/webpack': string;
        readonly 'css-loader': string;
        readonly 'escape-string-regexp': string;
        readonly 'fs-extra': string;
        readonly glob: string;
        readonly minimist: string;
        readonly mocha: string;
        readonly rimraf: string;
        readonly 'source-map-support': string;
        readonly 'ts-loader': string;
        readonly typescript: string;
        readonly webpack: string;
    };
    readonly dependencies: {
        readonly 'loader-utils': string;
    };
}
export default __jsonRoot;

// Named exports with top level propeties whose names are valid identifiers
export const name: string;
export const version: string;
export const description: string;
export const main: string;
export const scripts: {
    readonly 'clean:lib': string;
    readonly 'prebuild:lib': string;
    readonly 'build:lib': string;
    readonly 'clean:test': string;
    readonly 'prebuild:test': string;
    readonly 'build:test': string;
    readonly build: string;
    readonly prewatch: string;
    readonly watch: string;
    readonly pretest: string;
    readonly test: string;
    readonly prepublishOnly: string;
};
export const repository: {
    readonly 'type': string;
    readonly url: string;
};
export const keywords: [
    string,
    string,
    string,
    string,
    string,
    string,
    string
];
export const author: string;
export const license: string;
export const bugs: {
    readonly url: string;
};
export const homepage: string;
export const devDependencies: {
    readonly '@types/escape-string-regexp': string;
    readonly '@types/fs-extra': string;
    readonly '@types/glob': string;
    readonly '@types/minimist': string;
    readonly '@types/mocha': string;
    readonly '@types/rimraf': string;
    readonly '@types/webpack': string;
    readonly 'css-loader': string;
    readonly 'escape-string-regexp': string;
    readonly 'fs-extra': string;
    readonly glob: string;
    readonly minimist: string;
    readonly mocha: string;
    readonly rimraf: string;
    readonly 'source-map-support': string;
    readonly 'ts-loader': string;
    readonly typescript: string;
    readonly webpack: string;
};
export const dependencies: {
    readonly 'loader-utils': string;
};
